name: Generate OpenAPI Ruby Client
on:
  push:
    branches: [ main ]
jobs:
  generate-angular-client:
    runs-on: ubuntu-latest
    name: Generate OpenAPI Ruby Client
    steps:

      # Checkout your code
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      # Use the action to generate a client package
      # This uses the default path for the openapi document and thus assumes there is an openapi.json in the current workspace.
      - name: Generate Ruby Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: ruby
          config-file: src/openapi/templates/ruby/ruby-generator-config.json
          template-dir: src/openapi/templates/ruby
          openapi-file: eMASSRestOpenApi.yaml

      # Do something with the generated client (likely publishing it somewhere)
      - name: Publish Ruby Client (src/ruby_client)
        run: |
          echo "Generated ruby API client successfully."
          echo "Copying to repository..."
          sudo cp -R /github/workspace/ruby-client src/ruby_client
          echo "All done now."